[package]
name = "classitunes"
version = "1.4.0"
description = "ClassiTunes Music Player"
authors = ["Z Software Labs"]
edition = "2021"

[lib]
name = "classitunes_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri = { version = "2", features = ["protocol-asset"] }
tauri-plugin-opener = "2"
tauri-plugin-window-state = "2"
tauri-plugin-dialog = "2"
tauri-plugin-fs = "2"
id3 = "1.16"
mp4ameta = "0.13"
tauri-plugin-process = "2"
tiny_http = "0.12"
lofty = "0.25.3"
rayon = "1.10"

[profile.release]
codegen-units = 1
lto = true
opt-level = 3
panic = "abort"
strip = true

[profile.dev]
incremental = true

[target.'cfg(not(any(target_os = "android", target_os = "ios")))'.dependencies]
tauri-plugin-updater = "2"


